### ISSUE TITLE
请问sublime text如何引入swoole-auto-complete

### ISSUE THREAD

**Issue by xxluan** [eaglewu/swoole-ide-helper#21]
请问sublime text如何引入swoole-auto-complete

**Comment by eaglewu** [comment]
ST直接Copy swoole.php 到项目目录中.

使用Demo:
0、 swoole 文件加入项目目录
1、cmd + p (菜单栏 Goto Anything..)
2、输入 `swoole@swoole_server_handler`  回车跳转至函数

PS：好不爽~  ST毕竟只是编辑器， IDE 推荐使用 PHPStorm

**Comment by noname007** [comment]
可以配合插件[`All Autocomplete`](https://github.com/alienhard/SublimeAllAutocomplete)尝试一下。
