### ISSUE TITLE
English phpdoc

### ISSUE THREAD

**Issue by Atriedes** [eaglewu/swoole-ide-helper#25]
It would be nice if phpdoc comment translated to english

**Comment by SimonShia** [comment]
版本跟不上啊,现在都1.7.18了,这个代码提示才到1.7.7

**Comment by Atriedes** [comment]
yep there are some new API in 1.7.18, could you please translate it to english? So I can generate API docs based on your IDE helper

**Comment by eaglewu** [comment]
I will try do it.

**Comment by Atriedes** [comment]
thanks if possible could you please separate the class

please take a look my fork : https://github.com/Atriedes/swoole-ide-helper

I tried translate in english and make them easier to read, what do you think?

**Comment by eaglewu** [comment]
@Atriedes  Good Job! :+1: 
I will update the repository structure like yours in Chinese.
Busy at work.. so you know.. :)

**Comment by Atriedes** [comment]
Thanks I think its better, to make 1 repository rather than 2 for avoid confusion. Also it is possible to install it via composer.

Do you want me to send pull request?

Don't worry take your time friends :) I'm happy to maintain this project added new API in new version

**Comment by zhangxiaoliu** [comment]
使用 PHPStorm 自带 Include Path 功能引入，具体是怎么操作的？

**Comment by eaglewu** [comment]
@zhangxiaoliu  Screenshots
![d4469014-780b-4b46-a9f1-dc12cdd14266](https://cloud.githubusercontent.com/assets/3753615/12084347/18ff7522-b2ed-11e5-8f52-e9ea5e749c44.png)
![22e2e7d1-2049-49f7-b5ce-cf7ffc5bdc58](https://cloud.githubusercontent.com/assets/3753615/12084350/2f4e5320-b2ed-11e5-96ff-d2e14d688599.png)

**Comment by zhangxiaoliu** [comment]
@eaglewu  thank you
