### ISSUE TITLE
\Swoole\Coroutine::getuid() 所属类划分出错

### ISSUE THREAD

**Issue by jixianlqb** [eaglewu/swoole-ide-helper#57]
\Swoole\Coroutine::getuid()而不是\Swoole\Coroutine\Util::getuid()

**Comment by eaglewu** [comment]
Fix  e96f327ba69ac46532d5250ddb03f8492d435afc
Tks 👍

**Comment by eaglewu** [comment]
Composer 包已同步，请及时更新
