### ISSUE TITLE
Please make some release

### ISSUE THREAD

**Issue by xiaohuilam** [eaglewu/swoole-ide-helper#67]
Reason: if not make version, packagist will not cache code.
Better keep version with swoole-src's.

**Comment by eaglewu** [comment]
> I saw you are Chinese, so let's talk  in Chinese :)

该仓库代码、案例、注释说明会随时更新，并非与官方 `swoole-src` 源代码版本同步，推荐使用下面 `--dev` 方式引入。
`composer require --dev "eaglewu/swoole-ide-helper:dev-master"`
相应的，并不推荐对该仓库代码进行缓存。
